version: '1'

services:
  flask-app:
    build: 
      context: ..
      dockerfile: Docker/Dockerfile
    image: to-do-app:latest 
    ports:
      - "5001:5000"
    depends_on:
      - mongo
    environment:
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - FLASK_ENV=development
      - PORT=5000

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
