apiVersion: v1
kind: ReplicationController
metadata:
  name: flask-app-rc
spec:
  replicas: 2  # Desired number of replicas
  selector:
    app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-app
        image: shettyniti/to-do-app:v2  # Docker Hub image
        ports:
        - containerPort: 5000
        env:
        - name: MONGO_HOST
          value: "mongo-service"  # Make sure this matches your MongoDB service
        - name: MONGO_PORT
          value: "27017"

